### ISSUE TITLE
how to make containers for this?

### ISSUE THREAD

**Issue by sam0x17** [genuinetools/binctr#11]
e.g. lets say I wanted to use an ubuntu 18.04 server container. How would I go about doing that? Does this use Docker? I'd be happy to add to the docs with this info once I know how.

**Comment by jessfraz** [comment]
copy one of the examples and change the image to ubuntu https://github.com/genuinetools/binctr/tree/master/examples/busybox

since ubuntu is a larger image though the binary will be larger since it includes a tarball of the image.
